### ISSUE TITLE
Method update in UsersController error

### ISSUE THREAD

**Issue by profeg** [javamentorship/mentorship#9]
Не работает валидация, не изменяет дату

**Comment by stokito** [comment]
1. Что хочешь сделать и зачем
2. Последовательность действий
3. Ожидаемый результат (expected)
4. Получаемый результат
5. Логи и настройка окружения, хеш комита или ветка в котором проблема

**Comment by stokito** [comment]
С датами ошибка как правило из-за разных форматов дат. В спринге есть аннотация что-то вроде Binding date format

**Comment by profeg** [comment]
Хочу обновить запись в таблице users, и в UsersController пишу метод:
@RequestMapping(value = "/update", method = RequestMethod.POST)
    public String update(@Valid @ModelAttribute("update_form") UsersUpdateForm updateForm, BindingResult result) {
        LOGGER.debug("Received request for UPDATE data in table USERS");
        if (result.hasErrors()) {
            return "users_update";
        } else {
            User user = usersDao.findOne(updateForm.getId());
            user.setLogin(updateForm.getLogin());
            user.setFirstName(updateForm.getFirstName());
            user.setSecondName(updateForm.getSecondName());
            user.setEmail(updateForm.getEmail());
            user.setDateCreated(updateForm.getDateCreated());
            user.setIsAdmin(updateForm.getIsAdmin());
            usersDao.save(user);
            return REDIRECT_TO_INDEX;
        }
    }
Но метод выбирает happy case при проверке result.hasErrors, а что за ошибка я разобраться не могу пока. Но вот если убрать все, что связано с валидацией, то обновляет все (кроме даты =). Вот так:
@RequestMapping(value = "/update", method = RequestMethod.POST)
    public String update(@Valid @ModelAttribute("update_form") UsersUpdateForm updateForm, BindingResult result) {
            User user = usersDao.findOne(updateForm.getId());
            user.setLogin(updateForm.getLogin());
            user.setFirstName(updateForm.getFirstName());
            user.setSecondName(updateForm.getSecondName());
            user.setEmail(updateForm.getEmail());
            user.setDateCreated(updateForm.getDateCreated());
            user.setIsAdmin(updateForm.getIsAdmin());
            usersDao.save(user);
            return REDIRECT_TO_INDEX;
     }
Вот хэш коммита 3f759c99d6a87a869698cd7e1f3b338f50eac8c5

**Comment by stokito** [comment]
Значит не прошла валидация даты. Т.е. преобразовать из строки в объкт `Date`
В дебагере нужно посмотреть на `BindingResult  result` внутри него есть коды ошибок.
Ещё раз повторю - нужно найти в спринговой документации как указать дейт формат для биндинга

**Comment by profeg** [comment]
да эта валидация в принципе не работает, тоесть добавляются пустые записи, везде кстати во всех таблицах
